# environment.yml

name: cerna-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=7.32.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - requests
  - jinja2
  - pip
  - pip:
      - xgboost
      - torch
      - torch-geometric
      - statsmodels
      - plotly
      - rpy2
